// Minecraft Beta 1.7.3 Style Perlin Noise Implementation for Unity
// This file replicates the behavior of NoiseGeneratorPerlin.java
//
// How to Use:
// 1. Save this file as "MinecraftB173Noise.cginc" in your Unity project's Assets folder.
// 2. In your shader, include it with: #include "Assets/MinecraftB173Noise.cginc"
// 3. Call the noise function in your fragment or vertex shader:
//    float noiseValue = mcn_noise(float3(pos.x * frequency, pos.y * frequency, pos.z * frequency));
//
// Note: The permutation array `p` is hardcoded here. In the original Java code, it's
// initialized using a seeded java.util.Random instance. To get different worlds,
// you would need to regenerate and replace this array using a new seed. This
// implementation uses the default permutation array generated with a seed of 0.

#ifndef MC_B173_NOISE_INCLUDED
#define MC_B173_NOISE_INCLUDED

// --- Data Structures ---

// The permutation array is now loaded from a texture instead of being hardcoded.
// The texture should be a 256x2 R8 texture where:
// - Row 0 (y=0): Contains permutation values 0-255
// - Row 1 (y=1): Contains the same values (duplicate for wraparound)
sampler2D _Udon_PermutationTex;

// Helper function to sample the permutation texture
int mcn_sample_perm(int index)
{
    // Ensure index is in valid range [0, 511]
    index = index & 511;
    
    // Calculate texture coordinates
    // x = index % 256 (mapped to 0-1 range)
    // y = index / 256 (0 for first 256 values, 1 for second 256)
    float2 uv;
    uv.x = (float)(index & 255) / 255.0 + 0.5/256.0; // Add half-pixel offset for accurate sampling
    uv.y = (float)(index >> 8) * 0.5 + 0.25; // 0.25 for row 0, 0.75 for row 1
    
    // Sample the texture and convert back to integer [0, 255]
    float val = tex2Dlod(_Udon_PermutationTex, float4(uv, 0, 0)).r;
    return (int)(val * 255.0 + 0.5);
}

//Put the block lookup tables between these. This way we don't have to marshal the data between the CPU and GPU.
// BLOCK_LOOKUP_TABLES_START
// This code is auto-generated by BlockPropertiesBaker.cs. DO NOT EDIT MANUALLY.
static const uint BLOCK_PROPERTIES_LUT[25] = {
    0x002Eu, // Block ID: 0 (Air)
    0x0011u, // Block ID: 1 (Stone)
    0x0111u, // Block ID: 2 (Grass)
    0x0011u, // Block ID: 3 (Dirt)
    0x0029u, // Block ID: 4 (Cobblestone)
    0x0029u, // Block ID: 5 (Planks)
    0x0044u, // Block ID: 6 (Oak_Sapling)
    0x0011u, // Block ID: 7 (Bedrock)
    0x0012u, // Block ID: 8 (Water_Still)
    0x0012u, // Block ID: 9 (Water_Flowing)
    0x0012u, // Block ID: 10 (Lava_Still)
    0x0012u, // Block ID: 11 (Lava_Flowing)
    0x0029u, // Block ID: 12 (Sand)
    0x0029u, // Block ID: 13 (Gravel)
    0x0029u, // Block ID: 14 (Gold_Ore)
    0x0029u, // Block ID: 15 (Iron_Ore)
    0x0029u, // Block ID: 16 (Coal_Ore)
    0x0111u, // Block ID: 17 (Log)
    0x0005u, // Block ID: 18 (Leaves)
    0x0029u, // Block ID: 19 (Sponge)
    0x0015u, // Block ID: 20 (Glass)
    0x0029u, // Block ID: 21 (Lapis_Lazuli_Ore)
    0x0029u, // Block ID: 22 (Lapis_Lazuli_Block)
    0x0129u, // Block ID: 23 (Dispenser)
    0x0111u // Block ID: 24 (Sandstone)
};

// --- Helper functions to unpack data from BLOCK_PROPERTIES_LUT ---
// Note: The bit shifts and masks MUST match McBlockTypeManager.EncodeDataForBuild()

bool get_is_solid(uint block_id) {
    return (BLOCK_PROPERTIES_LUT[block_id] & 0x1u) != 0u; // Bit 0
}

uint get_visibility_type(uint block_id) {
    return (BLOCK_PROPERTIES_LUT[block_id] >> 1) & 0x3u; // Bits 1-2. 0:Opaque, 1:Transparent, 2:Cutout, 3:Invisible
}

uint get_culling_type(uint block_id) {
    return (BLOCK_PROPERTIES_LUT[block_id] >> 3) & 0x7u; // Bits 3-5. 0:NoCull, 1:CullSelf, 2:CullSelfAndOpaque, 3:CullSelfAndCutout, 4:CullSelfAndTransparent, 5:CullAll
}

uint get_shape_type(uint block_id) {
    return (BLOCK_PROPERTIES_LUT[block_id] >> 6) & 0x3u; // Bits 6-7. 0:Cube, 1:Cross
}

uint get_texture_mapping_type(uint block_id) {
    return (BLOCK_PROPERTIES_LUT[block_id] >> 8) & 0x3u; // Bits 8-9. 0:AllFacesSame, 1:TopBottomSides
}
// End of auto-generated code.

// BLOCK_LOOKUP_TABLES_END

// --- Helper Functions ---

// The fade function, which is a 5th-degree polynomial: 6t^5 - 15t^4 + 10t^3
// This creates a smoother interpolation than linear.
float mcn_fade(float t) {
    return t * t * t * (t * (t * 6.0 - 15.0) + 10.0);
}

// Linear interpolation
float mcn_lerp(float t, float a, float b) {
    return a + t * (b - a);
}

// Gradient function. Selects a 3D gradient vector from a pre-defined set
// based on the hash value.
float3 mcn_grad(int hash, float3 p) {
    int h = hash & 15;
    // In Java, this was done with a switch statement.
    // Here, we use direct selection based on the hash.
    float u = h < 8 ? p.x : p.y;
    float v = h < 4 ? p.y : (h == 12 || h == 14 ? p.x : p.z);
    return ((h & 1) == 0 ? u : -u) + ((h & 2) == 0 ? v : -v);
}

// --- Main Noise Function ---

// 3D Perlin Noise function
float mcn_noise(float3 pos) {
    // 1. Find the unit cube that contains the point
    float3 floor_pos = floor(pos);
    int X = (int)floor_pos.x & 255;
    int Y = (int)floor_pos.y & 255;
    int Z = (int)floor_pos.z & 255;

    // 2. Find relative X,Y,Z of point in cube
    pos -= floor_pos;

    // 3. Compute fade curves for each of X,Y,Z
    float u = mcn_fade(pos.x);
    float v = mcn_fade(pos.y);
    float w = mcn_fade(pos.z);

    // 4. Hash coordinates of the 8 cube corners
    int A = mcn_sample_perm(X) + Y;
    int AA = mcn_sample_perm(A) + Z;
    int AB = mcn_sample_perm(A + 1) + Z;
    int B = mcn_sample_perm(X + 1) + Y;
    int BA = mcn_sample_perm(B) + Z;
    int BB = mcn_sample_perm(B + 1) + Z;

    // 5. Add blended results from 8 corners of the cube
    float res = mcn_lerp(w, mcn_lerp(v, mcn_lerp(u, dot(mcn_grad(mcn_sample_perm(AA), pos), pos),
                                                     dot(mcn_grad(mcn_sample_perm(BA), pos - float3(1, 0, 0)), pos - float3(1, 0, 0))),
                                           mcn_lerp(u, dot(mcn_grad(mcn_sample_perm(AB), pos - float3(0, 1, 0)), pos - float3(0, 1, 0)),
                                                     dot(mcn_grad(mcn_sample_perm(BB), pos - float3(1, 1, 0)), pos - float3(1, 1, 0)))),
                              mcn_lerp(v, mcn_lerp(u, dot(mcn_grad(mcn_sample_perm(AA + 1), pos - float3(0, 0, 1)), pos - float3(0, 0, 1)),
                                                     dot(mcn_grad(mcn_sample_perm(BA + 1), pos - float3(1, 0, 1)), pos - float3(1, 0, 1))),
                                           mcn_lerp(u, dot(mcn_grad(mcn_sample_perm(AB + 1), pos - float3(0, 1, 1)), pos - float3(0, 1, 1)),
                                                     dot(mcn_grad(mcn_sample_perm(BB + 1), pos - float3(1, 1, 1)), pos - float3(1, 1, 1)))));

    return res;
}

// Generates multi-octave 3D Perlin noise.
// This is the core function used by the Beta 1.7.3 terrain generator.
// It combines multiple "octaves" of noise at different frequencies and amplitudes.
float mcn_generate_octave_noise(float3 pos, int octaves)
{
    float total = 0.0;
    float amplitude = 1.0;
    float frequency = 1.0;
    float maxValue = 0.0;

    // Use a standard loop. Unity's compiler will unroll this for fixed octave counts.
    for (int i = 0; i < octaves; i++)
    {
        total += mcn_noise(pos * frequency) * amplitude;
        
        maxValue += amplitude;
        
        // For each octave, double the frequency and halve the amplitude.
        // This is standard practice for fractal noise.
        frequency *= 2.0;
        amplitude *= 0.5;
    }
    
    // Normalize the result to be between -1.0 and 1.0.
    return total / maxValue;
}

// --- Counterpart of McUtils.cs but for the GPU. ---

// Converts a 2D pixel coordinate from the unrolled data texture to a 3D local block coordinate.
// Assumes Y-major order.
fixed3 mcn_pixel_to_block(
    fixed2 pixel_coord, // The (x,y) coordinate of the pixel in the texture.
    fixed chunk_size_xz  // The size of the chunk in the X and Z dimensions.
    )
{
    // FIX: Use floor() to convert from pixel center (e.g., 15.5) to an integer index (e.g., 15)
    fixed block_y = floor(pixel_coord.y);
    fixed block_z = floor(pixel_coord.x / chunk_size_xz);
    fixed block_x = fmod(floor(pixel_coord.x), chunk_size_xz);
    return fixed3(block_x, block_y, block_z);
}

// Converts a 3D local block coordinate to a 2D pixel coordinate in the unrolled data texture.
// Assumes Y-major order.
fixed2 mcn_block_to_pixel(
    fixed3 block_pos,   // The local (x,y,z) coordinate of the block within the chunk.
    fixed chunk_size_xz // The size of the chunk in the X and Z dimensions.
    )
{
    fixed pixel_y = block_pos.y;
    fixed pixel_x = block_pos.z * chunk_size_xz + block_pos.x;
    return fixed2(pixel_x, pixel_y);
}

// Block pos to chunk pos
fixed3 mcn_block_to_chunk(
    fixed3 block_pos, // The block position to convert.
    fixed3 chunk_pos, // The chunk the block is in.
    fixed chunk_size_xz, // The size of the chunks in the X and Z directions.
    fixed chunk_size_y // The size of the chunks in the Y direction.
    )
{
    return block_pos - chunk_pos * fixed3(chunk_size_xz, chunk_size_y, chunk_size_xz);
}

// Block pos to world pos
fixed3 mcn_block_to_world(
    fixed3 block_pos, // The block position to convert.
    fixed3 chunk_pos, // The chunk the block is in.
    fixed chunk_size_xz, // The size of the chunks in the X and Z directions.
    fixed chunk_size_y // The size of the chunks in the Y direction.
    )
{
    return block_pos + chunk_pos * fixed3(chunk_size_xz, chunk_size_y, chunk_size_xz);
}

// Chunk pos to world pos
fixed3 mcn_chunk_to_world(
    fixed3 chunk_pos, // The target chunk position to convert.
    fixed chunk_size_xz, // The size of the chunks in the X and Z directions.
    fixed chunk_size_y // The size of the chunks in the Y direction.
    )
{
    return chunk_pos * fixed3(chunk_size_xz, chunk_size_y, chunk_size_xz);
}

// Reminder of chunk data structure
// Bits 0-7 = ID of block (0-255)
// Bit 8 = isSolid
// Bits 9-10 = visibility (opaque, transparent, or cutout. Fourth value is unused)
// Bits 11-15 = unused

// The bytes


#endif // MC_B173_NOISE_INCLUDED
